import { ActionGuard, adminService, navigationService, storageService } from "../../../services/index"
import type { Coach, Course, Room } from "../../../types/admin"
import { confirmAction, promptAction } from "../../../utils/modal"

type CatalogItem = (Course | Room | Coach) & { detail: string; kind: "courses" | "rooms" | "coaches" }
const guard = new ActionGuard()
Page({
  data: { tab: "courses" as "courses" | "rooms" | "coaches", items: [] as CatalogItem[], mode: "loading", message: "正在加载基础资料", error: "" },
  onLoad() { if (storageService.user()?.role !== "admin") return navigationService.routeForbidden(); void this.load() },
  select(e: WechatMiniprogram.TouchEvent) { this.setData({ tab: String(e.currentTarget.dataset.tab) as "courses" | "rooms" | "coaches" }); void this.load() },
  async load() { try { const result = this.data.tab === "courses" ? await adminService.courses() : this.data.tab === "rooms" ? await adminService.rooms() : await adminService.coaches(); const items = result.items.map(item => ({ ...item, kind: this.data.tab, detail: this.data.tab === "courses" ? `${(item as Course).durationMinutes} 分钟` : this.data.tab === "rooms" ? `容量 ${(item as Room).capacity} 人` : (item as Coach).hasAccount ? `账号 ${(item as Coach).username}` : "未开通账号" })); this.setData({ items, mode: items.length ? "ready" : "empty", message: items.length ? "" : "暂无资料" }) } catch { this.setData({ mode: "error", message: "基础资料加载失败" }) } },
  async create() { const name = await promptAction("新增基础资料", "请输入名称"); if (!name) return; let input: Record<string, unknown>; if (this.data.tab === "courses") { const duration = Number(await promptAction("课程时长", "分钟数")); if (!Number.isInteger(duration) || duration <= 0) return this.setData({ error: "课程时长必须为正整数" }); input = { name, durationMinutes: duration, difficulty: "all_levels", enabled: true } } else if (this.data.tab === "rooms") { const capacity = Number(await promptAction("教室容量", "人数")); if (!Number.isInteger(capacity) || capacity <= 0) return this.setData({ error: "教室容量必须为正整数" }); input = { name, capacity, enabled: true } } else input = { name, enabled: true }; await this.run(`create:${this.data.tab}`, () => adminService.createCatalog(this.data.tab, input)) },
  async rename(e: WechatMiniprogram.TouchEvent) { const id = String(e.currentTarget.dataset.id); const name = await promptAction("修改名称", "请输入新名称"); if (!name) return; await this.run(`rename:${id}`, () => adminService.updateCatalog(this.data.tab, id, { name })) },
  async toggle(e: WechatMiniprogram.TouchEvent) { const id = String(e.currentTarget.dataset.id); const enabled = e.currentTarget.dataset.enabled !== true; if (!await confirmAction(enabled ? "确认启用" : "确认停用", "历史业务数据不会被删除。")) return; await this.run(`toggle:${id}`, () => adminService.updateCatalog(this.data.tab, id, { enabled })) },
  async account(e: WechatMiniprogram.TouchEvent) { const id = String(e.currentTarget.dataset.id); const username = await promptAction("开通教练账号", "请输入用户名"); if (!username) return; const password = await promptAction("初始密码", "至少 8 位"); if (!password || password.length < 8) return this.setData({ error: "初始密码至少 8 位" }); if (!await confirmAction("确认开通", `创建教练账号 ${username}？`)) return; await this.run(`account:${id}`, () => adminService.createAccount("coaches", id, username, password)) },
  async reset(e: WechatMiniprogram.TouchEvent) { const id = String(e.currentTarget.dataset.id); const password = await promptAction("重置教练密码", "至少 8 位"); if (!password || password.length < 8) return this.setData({ error: "新密码至少 8 位" }); if (!await confirmAction("确认重置密码", "旧密码将立即失效。")) return; await this.run(`reset:${id}`, () => adminService.resetPassword("coaches", id, password)) },
  async run(id: string, task: () => Promise<unknown>) { try { await guard.run(id, task); wx.showToast({ title: "操作成功", icon: "success" }); await this.load() } catch { this.setData({ error: "操作失败，请检查填写内容" }) } },
})
